name: events-trigger
on:
  push:
  pull_request:
    types: [opened, closed, reopened, synchronize]
  issues:
    types: [opened]
jobs:
  event-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3
