name: myfirst-1
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline command
        run: |
          pwd
          node -v
          npm -v
          mkdir vamsi
          ls -la

  second-job-mac_os:
    runs-on: macos-latest
    steps:
      - name: vamsi's output
        run: sw_vers
  third-job-windows:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: 3rd_output
        run: Write-Output "success"
      - name: condition(error)
        run: doesnot exist
