name: workflow-trigger
on:
  workflow_run:
    workflows: ["events-trigger"]
    types:
      - completed
jobs:
  workflow-trigger-when-event-workflow-is-completed:
    runs-on: ubuntu-latest
    steps:
      - run: echo "i was triggered bcoz of the events-trigger is c-ompleted"
